import { describe, it, expect, beforeEach } from 'vitest';
import type { AppState, ContigInfo } from '../../src/core/State';
import { exportAGP } from '../../src/export/AGPWriter';
import { contigExclusion } from '../../src/curation/ContigExclusion';
import { parseAGP, deriveAGPPlan } from '../../src/formats/AGPParser';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeContig(
  name: string,
  index: number,
  length: number,
  scaffoldId: number | null = null,
  inverted = false,
): ContigInfo {
  return { name, originalIndex: index, length, pixelStart: 0, pixelEnd: 0, inverted, scaffoldId };
}

function makeAppState(contigs: ContigInfo[], contigOrder: number[]): AppState {
  return {
    map: {
      filename: 'test.pretext',
      textureSize: 1024,
      numMipMaps: 1,
      tileResolution: 1024,
      tilesPerDimension: 1,
      contigs,
      contactMap: null,
      rawTiles: null,
      parsedHeader: null,
      extensions: new Map(),
    },
    contigOrder,
  } as unknown as AppState;
}

function nameToIdMap(contigs: ContigInfo[]): Map<string, number> {
  const m = new Map<string, number>();
  contigs.forEach((c, i) => m.set(c.name, i));
  return m;
}

// ---------------------------------------------------------------------------
// parseAGP
// ---------------------------------------------------------------------------

describe('parseAGP', () => {
  it('extracts W component rows, skipping comments, blanks, and gap lines', () => {
    const text = [
      '##agp-version\t2.1',
      '# Generated by OpenPretext',
      '',
      'scaffold_0\t1\t100\t1\tW\tctgA\t1\t100\t+',
      'scaffold_0\t101\t300\t2\tN\t200\tscaffold\tyes\tproximity_ligation',
      'scaffold_0\t301\t500\t3\tW\tctgB\t1\t200\t-',
      'unplaced_0\t1\t120\t1\tW\tctgC\t1\t120\t+',
    ].join('\n');

    const { rows } = parseAGP(text);
    expect(rows).toHaveLength(3);
    expect(rows.map((r) => r.contigName)).toEqual(['ctgA', 'ctgB', 'ctgC']);
    expect(rows.map((r) => r.inverted)).toEqual([false, true, false]);
    expect(rows.map((r) => r.objectName)).toEqual(['scaffold_0', 'scaffold_0', 'unplaced_0']);
    expect(rows.map((r) => r.isUnplaced)).toEqual([false, false, true]);
  });

  it('tolerates malformed lines without throwing', () => {
    const text = [
      'short\tline',
      'scaffold_0\t1\t100\t1\tW\tctgA\t1\t100\t+',
      'scaffold_0\t1\t100\t1\tZ\tctgX\t1\t100\t+', // unknown component type
      '\t1\t100\t1\tW\tctgNoObject\t1\t100\t+', // empty object
      'scaffold_0\t1\t100\t1\tW\t\t1\t100\t+', // empty componentId
      'not-a-tab-separated-line',
    ].join('\n');

    const { rows } = parseAGP(text);
    expect(rows).toHaveLength(1);
    expect(rows[0].contigName).toBe('ctgA');
  });

  it('returns no rows for empty input', () => {
    expect(parseAGP('').rows).toEqual([]);
    expect(parseAGP('# only a comment\n').rows).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Round-trip: AGPWriter export -> parseAGP -> deriveAGPPlan
// ---------------------------------------------------------------------------

describe('AGP import round-trip', () => {
  beforeEach(() => {
    // The exporter reads contigExclusion; ensure no leaked exclusion drops a contig.
    contigExclusion.clearAll();
  });

  it('recovers order, orientation, and scaffold grouping from AGPWriter output', () => {
    // Two scaffolds (ids 0 and 1) plus one unscaffolded contig.
    const contigs = [
      makeContig('ctgA', 0, 100, 0, false),
      makeContig('ctgB', 1, 200, 0, true), // inverted
      makeContig('ctgC', 2, 150, 1, false),
      makeContig('ctgD', 3, 120, null, false), // unscaffolded -> unplaced
    ];
    const order = [0, 1, 2, 3];
    const appState = makeAppState(contigs, order);

    const agpText = exportAGP(appState);
    const parsed = parseAGP(agpText);

    // Row order + orientation survive the round-trip.
    expect(parsed.rows.map((r) => r.contigName)).toEqual(['ctgA', 'ctgB', 'ctgC', 'ctgD']);
    expect(parsed.rows.map((r) => r.inverted)).toEqual([false, true, false, false]);

    // Grouping by object: scaffold_0 = {A,B}, scaffold_1 = {C}, unplaced_* = {D}.
    const dRow = parsed.rows.find((r) => r.contigName === 'ctgD')!;
    expect(dRow.isUnplaced).toBe(true);

    const plan = deriveAGPPlan(parsed, nameToIdMap(contigs), order);

    // No contig is dropped.
    expect(plan.newOrder).toHaveLength(contigs.length);
    expect(plan.newOrder).toEqual([0, 1, 2, 3]);
    expect(plan.matchedCount).toBe(4);
    expect(plan.unmatchedNames).toEqual([]);

    // Inversions recovered per contig id.
    expect(plan.inversions).toEqual([
      { id: 0, inverted: false },
      { id: 1, inverted: true },
      { id: 2, inverted: false },
      { id: 3, inverted: false },
    ]);

    // Two scaffold groups (unplaced singleton excluded), by order-index.
    expect(plan.scaffoldGroups).toHaveLength(2);
    expect(plan.scaffoldGroups[0].orderIndices).toEqual([0, 1]);
    expect(plan.scaffoldGroups[1].orderIndices).toEqual([2]);
  });

  it('applies a reordered AGP onto the loaded assembly', () => {
    // Loaded assembly is in one order; the AGP describes a different order
    // (a prior curation) with a scaffold spanning two contigs.
    const contigs = [
      makeContig('ctg1', 0, 100, null, false),
      makeContig('ctg2', 1, 200, null, false),
      makeContig('ctg3', 2, 150, null, false),
    ];
    const loadedOrder = [0, 1, 2];

    // Hand-built AGP: object chr1 holds ctg3 then ctg1 (ctg1 reverse), ctg2 unplaced.
    const agpText = [
      '##agp-version\t2.1',
      'chr1\t1\t150\t1\tW\tctg3\t1\t150\t+',
      'chr1\t151\t350\t2\tN\t200\tscaffold\tyes\tproximity_ligation',
      'chr1\t351\t450\t3\tW\tctg1\t1\t100\t-',
      'unplaced_0\t1\t200\t1\tW\tctg2\t1\t200\t+',
    ].join('\n');

    const parsed = parseAGP(agpText);
    const plan = deriveAGPPlan(parsed, nameToIdMap(contigs), loadedOrder);

    // New order: ctg3 (id 2), ctg1 (id 0), ctg2 (id 1) at the tail (in AGP too).
    expect(plan.newOrder).toEqual([2, 0, 1]);
    expect(plan.newOrder).toHaveLength(3);
    expect(plan.inversions).toEqual([
      { id: 2, inverted: false },
      { id: 0, inverted: true },
      { id: 1, inverted: false },
    ]);
    // One scaffold (chr1) with order-indices [0, 1] in the new order.
    expect(plan.scaffoldGroups).toHaveLength(1);
    expect(plan.scaffoldGroups[0].name).toBe('chr1');
    expect(plan.scaffoldGroups[0].orderIndices).toEqual([0, 1]);
  });

  it('appends loaded contigs absent from the AGP at the tail', () => {
    const contigs = [
      makeContig('ctg1', 0, 100, null, false),
      makeContig('ctg2', 1, 200, null, false),
      makeContig('ctg3', 2, 150, null, false),
    ];
    // AGP only mentions ctg2.
    const agpText = 'scaffold_0\t1\t200\t1\tW\tctg2\t1\t200\t+';
    const plan = deriveAGPPlan(parseAGP(agpText), nameToIdMap(contigs), [0, 1, 2]);

    expect(plan.matchedCount).toBe(1);
    expect(plan.newOrder).toHaveLength(3); // nothing dropped
    expect(plan.newOrder[0]).toBe(1); // ctg2 first (from AGP)
    expect(plan.newOrder.slice(1).sort()).toEqual([0, 2]); // ctg1, ctg3 appended
  });

  it('reports unmatched AGP rows and ignores duplicate contig names', () => {
    const contigs = [makeContig('ctg1', 0, 100, null, false)];
    const agpText = [
      'scaffold_0\t1\t100\t1\tW\tctg1\t1\t100\t+',
      'scaffold_0\t101\t200\t2\tW\tctg1\t1\t100\t-', // duplicate id
      'scaffold_0\t201\t300\t3\tW\tghost\t1\t100\t+', // unmatched
    ].join('\n');

    const plan = deriveAGPPlan(parseAGP(agpText), nameToIdMap(contigs), [0]);
    expect(plan.newOrder).toEqual([0]); // duplicate not added twice
    expect(plan.unmatchedNames).toEqual(['ghost']);
    // First occurrence wins for inversion.
    expect(plan.inversions).toEqual([{ id: 0, inverted: false }]);
  });

  it('returns matchedCount 0 when no names match', () => {
    const contigs = [makeContig('ctg1', 0, 100, null, false)];
    const agpText = 'scaffold_0\t1\t100\t1\tW\tnope\t1\t100\t+';
    const plan = deriveAGPPlan(parseAGP(agpText), nameToIdMap(contigs), [0]);
    expect(plan.matchedCount).toBe(0);
    expect(plan.newOrder).toEqual([0]); // loaded contig still preserved
    expect(plan.scaffoldGroups).toEqual([]);
  });
});
