/**
 * Pins how a .pretext map is matched against a published curated AGP.
 *
 * The comparison is directional and the direction is easy to get backwards. A
 * curator places some scaffolds into chromosomes and leaves the rest unplaced, so
 * a healthy pair always has map contigs absent from the AGP. Relatability means
 * every AGP component resolves to a contig in the map, not the reverse. Scoring it
 * the wrong way round reported the real quail pair (485 of 485 components resolved,
 * 160 contigs left unplaced) as unrelatable.
 */

import { describe, it, expect } from 'vitest';
import { parseAgpComponents, alignNames } from '../../bench/case-study-check';

const AGP = [
  '##agp-version\t2.1',
  '# DESCRIPTION: Generated by PretextView Version 0.2.5',
  'Scaffold_1\t1\t100\t1\tW\tH1.scaffold_35\t1\t100\t+\tPainted',
  'Scaffold_1\t101\t200\t2\tN\t100\tscaffold\tyes\tproximity_ligation',
  'Scaffold_1\t201\t300\t3\tW\tH1.scaffold_1\t1\t100\t+\tPainted',
  'Scaffold_2\t1\t100\t1\tW\tH2.scaffold_7\t1\t100\t-\tPainted',
].join('\n');

describe('case-study AGP parsing', () => {
  it('reads only the W rows and keeps object, component, and orientation', () => {
    const rows = parseAgpComponents(AGP);
    expect(rows).toHaveLength(3);
    expect(rows[0]).toEqual({ object: 'Scaffold_1', component: 'H1.scaffold_35', orientation: '+' });
    expect(rows[2]).toEqual({ object: 'Scaffold_2', component: 'H2.scaffold_7', orientation: '-' });
  });

  it('skips gap rows, comments, and blank lines', () => {
    expect(parseAgpComponents('')).toHaveLength(0);
    expect(parseAgpComponents('# only a comment')).toHaveLength(0);
    const gapOnly = 'Scaffold_1\t101\t200\t2\tN\t100\tscaffold\tyes\tproximity_ligation';
    expect(parseAgpComponents(gapOnly)).toHaveLength(0);
  });
});

describe('case-study map/AGP alignment', () => {
  const agp = parseAgpComponents(AGP);

  it('counts a pair as relatable when every component resolves, despite unplaced contigs', () => {
    const map = ['H1.scaffold_35', 'H1.scaffold_1', 'H2.scaffold_7', 'H1.scaffold_99', 'H1.scaffold_100'];
    const a = alignNames(map, agp);

    expect(a.unresolved).toEqual([]);
    expect(a.resolved).toHaveLength(3);
    // The two extras are the curator's unplaced scaffolds, not a mismatch.
    expect(a.unplaced).toEqual(['H1.scaffold_100', 'H1.scaffold_99']);
    expect(a.mapContigs).toBe(5);
  });

  it('flags a component the map cannot supply', () => {
    const map = ['H1.scaffold_35', 'H1.scaffold_1'];
    const a = alignNames(map, agp);
    expect(a.unresolved).toEqual(['H2.scaffold_7']);
  });

  it('reports object and component counts from the AGP, not the map', () => {
    const a = alignNames(['H1.scaffold_1'], agp);
    expect(a.agpRows).toBe(3);
    expect(a.agpComponents).toBe(3);
    expect(a.agpObjects).toBe(2);
  });

  it('does not treat a repeated component as two components', () => {
    // A scaffold the curator cut appears as several W rows into the same component.
    const repeated = parseAgpComponents(
      [
        'Scaffold_1\t1\t100\t1\tW\tH1.scaffold_1\t1\t100\t+\tPainted',
        'Scaffold_3\t1\t100\t1\tW\tH1.scaffold_1\t101\t200\t+\tPainted',
      ].join('\n'),
    );
    const a = alignNames(['H1.scaffold_1'], repeated);
    expect(a.agpRows).toBe(2);
    expect(a.agpComponents).toBe(1);
    expect(a.unresolved).toEqual([]);
  });
});
